### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by Kriss322** [BME-MIT-IET/Csapatnev-iet-2019#3]
Working on CI

**Comment by remenyi** [comment]
@abarcsa did the same thing in committing 23008b4fcac59ac817e3a9455c0c1c624b6e4926 to master, as @Kriss322 did on branch dev-CI. This is a problem we need to talk about. I think we should create separate branches for our issues, and then merge them into master when we feel that they are ready. This means that no one should directly commit to master.

On the other hand, making CI work with Travis must have been easy, considering the already existing .travis.yml file (which I failed to upload with the initial commit). I think we should start working on an another task from the first group. Running static analysis should show us lots of problems to be fixed. What do you guys think?
